# Generated by Django 5.1 on 2025-04-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpreferences',
            table='userPreferences',
        ),
    ]
