# Generated by Django 5.1 on 2025-04-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userpreferences_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='cooking_level',
            field=models.TextField(blank=True),
        ),
    ]
